### ISSUE TITLE
Allow several directives in one line

### ISSUE THREAD

**Issue by IvanSanchez** [IvanSanchez/Leafdoc#5]
From a conversation with @mourner:

> add the ability to separate docs directives with ; on the same line instead of line break, just to make things terser in some cases

> ``` 
/*
@class Control.Attribution
@aka L.Control.Attribution; @inherits Control
*/

**Comment by mourner** [comment]
Also to separate directive and description:

```
// @method setPrefix(prefix: String): this; Sets the text before the attributions.
```
