### ISSUE TITLE
Allow un-inheritable sections

### ISSUE THREAD

**Issue by IvanSanchez** [IvanSanchez/Leafdoc#6]
Some sections don't make sense on the children classes - like extension methods in Leaflet's `Layer` or the static inheritance stuff in Leaflet's `Class`.

There should be a way, most likely in the build script (as a Leafdoc API) to switch off inheritance of some sections.

Rationale for that is that there might be a plugin developers API, or even several levels of API altogether, defined by which sections to show.

**Comment by mourner** [comment]
I find it unlikely that we'll publish several versions of the docs depending on whether we hide the additional sections or not. I think it would be easier to just make a directive and not care about displaying the sections.
