### ISSUE TITLE
Finish up miniclasses support

### ISSUE THREAD

**Issue by IvanSanchez** [IvanSanchez/Leafdoc#7]
"Miniclasses" are being parsed, but rendered as normal classes/namespaces.

When stringifying a namespace, skip the class if it's a miniclass, and iterate through miniclasses after all sections have been outputted, to render miniclasses for a class.

**Comment by mourner** [comment]
What is a miniclass? Options/etc?

**Comment by IvanSanchez** [comment]
A "miniclass" is the best name I could find for a logical group of documentables that doesn't deserve a class by itself, but rather is displayed within another class.

There are two instances of this in the 🍂let code: options for map methods ("fitBounds options", etc) and event types ("mouseevent", etc). I want them to behave as classes because they are both sets of options, but they should not have a class header, so I will make `fitBounds options` and `zoom options` and `locate options` be displayed inside the docs for `L.Map`.

**Comment by mourner** [comment]
I know the name is pretty vague, but maybe something like `object` will sound better? All these cases are simply objects with a certain set of properties, and they're always instantiated as an object literal rather than through factory or constructor.

**Comment by IvanSanchez** [comment]
@mourner That'd be too confusing, I guess. This being focused on Javascript, I'd rather stay away from `object`, because functions are objects and methods are objects and prototypes are objects so a class method is an object (function) property of an object (prototype) property of an object (class constructor function) and then you user's brain cells stop working. :confounded: 

Also, as of now, a set of properties and a set of events and a set of methods is called a `class` (or a `namespace`). So (at least for me) it seems logical to have `class` somewhere in the name. Another option could be something like `subnamespace` or `mininamespace` or whatever.

I don't really care much about the naming (PRs to change stuff are welcome, y'a know). I just care that the output resembles the current leaflet docs as closely as possible.

**Comment by trusktr** [comment]
How's a miniclass different than a section?
